### ISSUE TITLE
Reduce automated testing for JDK8 Hotspot on s390x

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#116]
**Summary**

The regular testing for JDK8 Hotspot on s390x is to be reduced to sanity.OpenJDK only.

**Reasoning**

The lack of a JIT on JDK8 Hotspot for s390x results in runtimes for tests being many times longer than on other platforms.

Couple that with finite s390x runtime and minimal demand for this build, and the need for the testing fails to justify the excessive time cost.

This matter was discussed at the recent ACC (link below), and the consensus among attendees was to reduce automated testing for JDK8 Hotspot on s390x to sanity.OpenJDK only.

**PR**

Link to follow.

**Linked Issues**

[TSC issue 218: "Proposal: Scale back Hotspot JDK8 zLinux Effort"](https://github.com/AdoptOpenJDK/TSC/issues/218)
[TSC issue 217: "Bi-weekly Adoptium Community Call - April 5, 2021"](https://github.com/AdoptOpenJDK/TSC/issues/217)

**Comment by smlambert** [comment]
@adamfarley - likely need an if statement somewhere in the [runAqaTests](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L313) method, because essentially for jdk8/hs/s390x want to reduce the [buildConfig.TEST_LIST](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L322) and unfortunately the way to override the testList (where defaults are defined in [defaults.json](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/defaults.json#L35-L49)) is in the [jdk8u_pipeline_config.groovy](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/configurations/jdk8u_pipeline_config.groovy#L75-L79) file, where it is not clear to me you could reduce test from default to openjdk.sanity for just hotspot and leave default for openj9, or not.


@sophia-guo is very familiar with this code, so I defer to her advice

**Comment by adamfarley** [comment]
@sophia-guo - Here's a quick thought on the code, based on Shelley's comment above.

https://github.com/adoptium/ci-jenkins-pipelines/compare/master...adamfarley:reduce_s390x_jdk8_hs_testing

 It does mean that the job would be ignoring the parameters, whether set automatically or by the user. Is there a better way for us to exclude these tests?

**Comment by AdamBrousseau** [comment]
You should be able to exclude by overriding in the pipeline config as Shelley mentioned. However, it appears you'll also need to update this line in order to use different values for each variant.
https://github.com/adoptium/ci-jenkins-pipelines/blob/5d5fe7b2c5afe999f3a2554825f0f6cb3790668a/pipelines/build/common/build_base_file.groovy#L117

**Comment by sophia-guo** [comment]
I would suggest to do this when testList is generated,  so test running won't need to check it in each iteration.  The code can added after [this line](https://github.com/adoptium/ci-jenkins-pipelines/blob/5d5fe7b2c5afe999f3a2554825f0f6cb3790668a/pipelines/build/common/build_base_file.groovy#L236) .

Something like

```
        if (configuration.arch == 's390x' && !(configuration.os == 'linux' && configuration.java_tobuild == 'jdk8u') && configuration.variant == 'hotspot') {
            reset testList with only one element (sanity.openjdk);
        }
```

**Comment by AdamBrousseau** [comment]
@sophia-guo I don't see why you wouldn't set it in jdk8u_pipeline_config.groovy. You would need to modify the getTestList call and function but then it would be done properly. If you hack it out with an `if` you are creating special cases and making the code harder to follow imo. Yes it would be slightly more work but it would be worth the extra effort as I could see this use case happening again.

**Comment by sophia-guo** [comment]
@AdamBrousseau did you mean redesigning test element in Config class in jdk*u_pipelien_config? Something like 

```
                test                : [
                        hotspot     : [sanity.openjdk],
                        openj9      :  default
                ],
```

This way each platform and each impl could set its own testList, which is kind of similar to what we've done before -- each platform define it's own testList. I'm not sure if this requirement happens a lot?

**Comment by smlambert** [comment]
adding one more idea (hopefully not further muddying this story), but I envision other platforms where we:
- do not have machine resource
- just newly added platform and not ready for 'all the tests',
- no JIT and testing is too painfully slow 

Where we may wish to use a _minimalTestingDefault_  containing only sanity.openjdk to [testDetails in defaults.json](https://github.com/adoptium/ci-jenkins-pipelines/blob/5d5fe7b2c5afe999f3a2554825f0f6cb3790668a/pipelines/defaults.json#L34-L49)

**Comment by AdamBrousseau** [comment]
+1 Shelley. We could support more pre-defined lists in defaults. I have been doing so for "disabled_tests" as more of a comment so I don't lose track of targets. 

Sophia, yes like that plus the other changes I mentioned to handle the change in functionality.
