### ISSUE TITLE
Smoke tests failures didn't block the run-aqa tests as expected.

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/ci-jenkins-pipelines#121]
We'd like smoke tests failures would block the run-aqa tests.

Now if smoke tests job generation failed the run-aqa tests are blocked.
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16u/job/jdk16u-windows-x64-openj9/16/console

However if smoke tests job generate correctly but job itself failed, run-aqa test was not blocked as expected.
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16u/job/jdk16u-linux-x64-hotspot/15/console

Probably need to update https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L292

**Comment by sophia-guo** [comment]
Most of smokeTests jobs failed. Some of them are test failure

https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot_SmokeTests/1/console
Some of them shows no tests are running and job failed
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-dragonwell_SmokeTests/1/

**Comment by AdamBrousseau** [comment]
Just wanted to confirm whether or not these smoke tests will be a blocker in time for the release next week? I know we've failed them internally since they were added but I haven't had a chance to investigate.

**Comment by sophia-guo** [comment]
All smoke tests are limited to impl openj9 or vendors AdoptOpenJDK. There is no smoke tests for dragonwell ( impl=hotspot, vendor= alibaba) test jobs failed due to no test running `TOTAL: 0   EXECUTED: 0   PASSED: 0   FAILED: 0   DISABLED: 0   SKIPPED: 0`. 

@smlambert  should we just disable smoketest for dragonwell?

**Comment by smlambert** [comment]
@sophia-guo - we can either:
- disable for dragonwell **or** 
- add alibaba as vendor to Adopt_HS_FeatureTests target at [L35](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/test/functional/buildAndPackage/playlist.xml#L35) if those tests apply **or**
- create a new test target in the playlist for Dragonwell, with the [CommonFeatureTests and/or HotspotFeatureTests](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/test/functional/buildAndPackage/testng.xml#L18-L29)

Also, for the https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot_SmokeTests/1/console failure, [JdkPlatform.javaL65](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java#L65) needs to be updated to either add or replace the arch string to match on, as os.arch must be returning ppc64 instead of ppc64le

```
13:58:01  Caused by: java.lang.AssertionError: Unrecognized architecture: ppc64
13:58:01  	at net.adoptopenjdk.test.JdkPlatform.detectArchitecture(JdkPlatform.java:90)
13:58:01  	at net.adoptopenjdk.test.JdkPlatform.<init>(JdkPlatform.java:27)
13:58:01  	at net.adoptopenjdk.test.BundledFreetypeTest.<init>(BundledFreetypeTest.java:42)
```

**Comment by sophia-guo** [comment]
Move specific smoke test case failure to separate issue #127 as there are different failures. Fix would be in openjdk-build repos.

**Comment by zdtsw** [comment]
as part of issue https://github.com/adoptium/ci-jenkins-pipelines/issues/234

**Comment by zdtsw** [comment]
e.g in the release smoketest job:
-https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk19u/job/jdk19u-release-aix-ppc64-temurin_SmokeTests/1/console  -- unstable
-https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk8u/job/jdk8u-release-alpine-linux-x64-temurin_SmokeTests/2/console -- failed
they were not indicated in the upstream pipeline result. Mostly it is false alarm to release but could also be hidden problems.
for the non-temurin variant, we can move them to evaluation, but for the temurin'sgood to know what causes such

**Comment by smlambert** [comment]
has this now been completed and can be closed?
