### ISSUE TITLE
We should not require "sw.tool.docker" when run test job

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#528]
Currently, weekly pipeline on jdk17 is hanging, waiting for Test_openjdk17_hs_extended.openjdk_arm_linux to be finished

and job "Test_openjdk17_hs_extended.openjdk_arm_linux" is waiting for resource "‘ci.role.test&&sw.os.linux&&hw.arch.aarch32&&sw.tool.docker’" 
but seems we do not have any jenkins agent match this label.

This happens for jdk19 jobs as well: https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_extended.openjdk_arm_linux_testList_0/29/console

**Comment by sophia-guo** [comment]
sw.tool.docker was added as extra label, which shouldn't.

Might be related with https://github.com/adoptium/ci-jenkins-pipelines/pull/513/files#diff-b4bb07e2f448f9ad2986d69423ad0b704dcdc4d217d947f465e6ace3fde7a4b3. Will take a further look.

**Comment by smlambert** [comment]
Related to adding openjdk container tests:
https://github.com/adoptium/aqa-tests/issues/4143
https://github.com/adoptium/ci-jenkins-pipelines/issues/512 

Based on this [comment](https://github.com/adoptium/aqa-tests/issues/4143#issuecomment-1316657150), these tests should eventually run on many platforms, not sure if arm_linux is in the mix or not.

**Comment by sophia-guo** [comment]
Currently the label `sw.tool.docker` was added to all testTypes, which shouldn't. We are expected extra label `sw.tool.docker` added to `dev.openjdk` specifically. This is caused by the shared variable additionalTestLabel with parallel. https://github.com/adoptium/ci-jenkins-pipelines/pull/531 should fix this.

Though with https://github.com/adoptium/aqa-tests/issues/4143 ( limit to linux) and dev.openjdk enabled https://github.com/adoptium/ci-jenkins-pipelines/issues/501 there will be dev.openjdk jobs generated with non-linux platforms. These job will fail or hang due to no machine available. For example: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_dev.openjdk_aarch64_mac/.  https://github.com/adoptium/ci-jenkins-pipelines/pull/531  will not fix this.

**Comment by sophia-guo** [comment]
Currently dev.openjdk only has container tests, which are limited to `os.linux`.  That is even if there is no extra label `sw.tool.docker` requirement job dev.openjdk on non-linux platform will fail as no tests.

**Comment by jerboaa** [comment]
> Based on this [comment](https://github.com/adoptium/aqa-tests/issues/4143#issuecomment-1316657150), these tests should eventually run on many platforms, not sure if arm_linux is in the mix or not.

In theory, yes. If there is a working and supported base image to use. The default UBI 9 image isn't supported on that architecture (32 bit arm), though.

**Comment by llxia** [comment]
FYI @AdamBrousseau
