### ISSUE TITLE
Temurin RemoteJckTrigger needs to use AUTO_AQA_GEN=true

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#534]
Remote AQA_TEST_PIPELINE fails if the test job does not exist:
```
[Pipeline] echo
[WARNING] Requested test job that does not exist or is disabled: Test_openjdk8_hs_sanity.jck_aarch64_alpine-linux
[Pipeline] echo
TEST_JOB_NAME: Test_openjdk8_hs_extended.jck_aarch64_alpine-linux
```

**Comment by sophia-guo** [comment]
AUTO_AQA_GEN=true is used to force generate or regenerate all jobs related. We can also generate the job if it doesn't exist, the same way as smoke and aqa-tests.

**Comment by smlambert** [comment]
> https://github.com/adoptium/ci-jenkins-pipelines/issues/534#issuecomment-1346872231

I prefer to generate the job if it doesn't exist and not have to force regen all jobs as that can take a lot of time each time and is most often not needed.  

But also, the reason that job did not exist, must be that we do not release that platform/version combination, so perhaps we rethink what is running in the "stuff we officially release" pipeline.

**Comment by andrew-m-leonard** [comment]
Ah yes, did notice that, it was jdk8 aarch64_alpine-linux, so yes makes sense for the job to ignore it.
I guess the key thing is the necessary jobs are there and gen'd to the latest level before the release

**Comment by sophia-guo** [comment]
I checked the weekly run both upstream job and  AQA_TEST_PIPELINE passed with no test job exist. There is only warning information in console output. https://ci.eclipse.org/temurin-compliance/job/AQA_Test_Pipeline/370/ https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-alpine-linux-aarch64-temurin/111/console. That is no jobs will be affected by this behaviour. 

For weekly run (temurin variant) if we are only interested in the releasing platform/version combination we can update the weekly run (temurin variant) to use jdkversion_release.groovy (for example https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/configurations/jdk17u_release.groovy) instead of jdkversion.groovy. In this way if job doesn't exist we can generate it and also there will be no unnecessary job generated.

**Comment by andrew-m-leonard** [comment]
As mentioned above, for the moment this is desired behavior
