### ISSUE TITLE
No JDK11 or JDK17 AQAvit test jobs are triggered in recent runs

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#630]
JDK11 - Warning: No AQA Test Builds got triggered in this pipeline. Please check TRSS [build details](https://trss.adoptium.net/buildDetail?parentId=63fa4dde17052c67158fd51e) or Jenkins [openjdk11-pipeline #2279](https://ci.adoptium.net/job/build-scripts/job/openjdk11-pipeline/2279/).  
- Not sure why pipeline 2279 did not trigger any testing (enableTests = true, according to https://ci.adoptium.net/job/build-scripts/job/openjdk11-pipeline/2279/parameters/).

JDK17 - Warning: No AQA Test Builds got triggered in this pipeline. Please check TRSS [build details](https://trss.adoptium.net/buildDetail?parentId=63fb4c3a17052c6715a13178) or Jenkins [openjdk17-pipeline #632](https://ci.adoptium.net/job/build-scripts/job/openjdk17-pipeline/632/)

Additionally, no remote- triggered TCK tests were triggered (which we expect to happen during weekly runs).

Does not appear to be an issue with jdk8 or jdk20 (though they are on a different schedule?).

**Comment by zdtsw** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/blob/c1340f5d5661f1590152bd113956233f72bbecbb/pipelines/build/common/openjdk_build_pipeline.groovy#L487
is it because the job itself does not have "release" in the name? 
e.g https://ci.adoptium.net/job/build-scripts/job/openjdk11-pipeline/2279/  triggered https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/195 which did try to "remote trigger" TCK



As for "no AQA" , because 
```
20:05:37  No such property: buildconfig for class: Build
20:05:37  Possible solutions: buildConfig
```
https://github.com/adoptium/ci-jenkins-pipelines/blob/c1340f5d5661f1590152bd113956233f72bbecbb/pipelines/build/common/openjdk_build_pipeline.groovy#L1879
so the parallel tests are skipped

**Comment by sophia-guo** [comment]
This should be fixed by https://github.com/adoptium/ci-jenkins-pipelines/pull/633/files. That is aqa tests will be triggered this weekly run.  It would be nice to have a try catch block, which will not block the aqa-tests even there is issues with remote trigger. I will create a PR.
