### ISSUE TITLE
Additional test label for jdk20+

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/ci-jenkins-pipelines#970]
JDK20+ won't run on anything earlier than about RHEL7 .  Tests need to be limited to run on RHEL7 ( if it's hit a RHEL6/CentOS6 box that could be the problem  ).

@sxa

**Comment by sxa** [comment]
SGTM - can you make the changes to add in the exclusion for machines with the appropriate labels in the pipelines?

**Comment by Haroon-Khel** [comment]
> Tests need to be limited to run on RHEL7

Do you mean RHEL7+ or does this mean they cannot be run on RHEL/Centos 8?

**Comment by sxa** [comment]
It will be fine on 8+. This is due to the glibc version on RHEL6 being too low for JDK21+ since [we switched that version for x64 to build on RHEL7](https://github.com/adoptium/ci-jenkins-pipelines/pull/627). The goal here is to stop it running on any Centos/RHEL6 system. They must still be able to run on other distributions (AFAIK all of our other ones in the CI are of a suitable glibc level - you can see which is in each on [our platforms wiki page](https://github.com/adoptium/infrastructure/wiki/End-of-support-date-for-OS-distributions))
